apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: defectdojo
  namespace: default
spec:
  rules:
  - host: defectdojo.mindcomputing.info
    http:
      paths:
      - backend:
          serviceName: defectdojo-django
          servicePort: 80
        path: /(.*)
        pathType: Prefix
  tls:
  - hosts:
    - defectdojo.mindcomputing.info
    secretName: aks-ingress-tls
